# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: demo.proto for package 'demo'

require 'grpc'
require 'demo_pb'

module Demo
  module DemoService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'demo.DemoService'

      rpc :SayHello, HelloRequest, HelloResponse
      rpc :Sum, SumRequest, SumResponse
    end

    Stub = Service.rpc_stub_class
  end
end
